apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: foundationlayer
  source:
    repoURL: 'https://github.com/celigo/foundational-layers-helm-values'
    path: istio-base
    targetRevision: "${env}"
    helm:
      releaseName: istio-base
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
